version: '3'

services:
  card-tokenization-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - redis

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

  test-runner:
      build:
        context: .
        dockerfile: Dockerfile.tests
      depends_on:
        - redis